language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t jeff/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e CI=true jeff/react-test npm test 

after_success:
  - docker build -t techjeffyu/multi-client:latest ./client
  - docker build -t techjeffyu/multi-nginx:latest ./nginx
  - docker build -t techjeffyu/multi-server:latest ./server
  - docker build -t techjeffyu/multi-worker:latest ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push techjeffyu/multi-client:latest
  - docker push techjeffyu/multi-nginx:latest
  - docker push techjeffyu/multi-server:latest
  - docker push techjeffyu/multi-worker:latest
#Log in to the docker CLI


