language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t jeff/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e CI=true jeff/react-test npm test 

after_success:
  - docker build -t jeff/multi-client ./client
  - docker build -t jeff/multi-nginx ./nginx
  - docker build -t jeff/multi-server ./server
  - docker build -t jeff/multi-worker ./worker

